# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}

# Optimisation
opt_design 
write_checkpoint -force ${::top}_opt.dcp
create_report "opt_report_drc_0" "report_drc -file ${::top}_drc_opted.rpt -pb ${::top}_drc_opted.pb -rpx ${::top}_drc_opted.rpx"

# Place
if { [llength [get_debug_cores -quiet] ] > 0 }  { 
  implement_debug_core 
} 
place_design -directive $::place_directive
write_checkpoint -force ${::top}_placed.dcp
create_report "place_report_io_0" "report_io -file ${::top}_io_placed.rpt"
create_report "place_report_utilization_0" "report_utilization -file ${::top}_utilization_placed.rpt -pb ${::top}_utilization_placed.pb"
create_report "place_report_control_sets_0" "report_control_sets -verbose -file ${::top}_control_sets_placed.rpt"

# Physical optimisation
phys_opt_design -directive $::phys_opt_directive
write_checkpoint -force ${::top}_physopt.dcp

# Route
route_design -directive $::route_directive
write_checkpoint -force ${::top}_routed.dcp
create_report "route_report_drc_0" "report_drc -file ${::top}_drc_routed.rpt -pb ${::top}_drc_routed.pb -rpx ${::top}_drc_routed.rpx"
create_report "route_report_methodology_0" "report_methodology -file ${::top}_methodology_drc_routed.rpt -pb ${::top}_methodology_drc_routed.pb -rpx ${::top}_methodology_drc_routed.rpx"
create_report "route_report_power_0" "report_power -file ${::top}_power_routed.rpt -pb ${::top}_power_summary_routed.pb -rpx ${::top}_power_routed.rpx"
create_report "route_report_route_status_0" "report_route_status -file ${::top}_route_status.rpt -pb ${::top}_route_status.pb"
create_report "route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file ${::top}_timing_summary_routed.rpt -pb ${::top}_timing_summary_routed.pb -rpx ${::top}_timing_summary_routed.rpx -warn_on_violation "
create_report "route_report_incremental_reuse_0" "report_incremental_reuse -file ${::top}_incremental_reuse_routed.rpt"
create_report "route_report_clock_utilization_0" "report_clock_utilization -file ${::top}_clock_utilization_routed.rpt"
create_report "route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file ${::top}_bus_skew_routed.rpt -pb ${::top}_bus_skew_routed.pb -rpx ${::top}_bus_skew_routed.rpx"


