# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc [file join $::constrsDir new/p6003_2_synth.xdc]
set_property used_in_implementation false [get_files [file join $::constrsDir new/p6003_2_synth.xdc] ]

set_param ips.enableIPCacheLiteLoad 1

synth_design -top $::top -part $::part -directive $::synth_directive -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ${::top}_synth.dcp
create_report "synth_report_utilization" "report_utilization -file ${::top}_utilization_synth.rpt -pb ${::top}_utilization_synth.pb"
create_report "synth_report_timing" "report_timing_summary -file ${::top}_timing.rpt"
